language: node_js

os:
  - linux
  - osx
  - windows

node_js:
  - "17"
  - "16"
  - "15"
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"

sudo: required

addons:
  chrome: stable

script:
  - npm run e2e
